apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: raft-chat-bot-marketing-web-init
  name: raft-chat-bot-marketing-web-init
  namespace: raft-chat-bot-marketing
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - image: raft-chat-bot-marketing-image:latest
        imagePullPolicy: Never
        name: raft-chat-bot-marketing-web
        command:
          - pip install -r requirements.txt
        volumeMounts:
          - name: code
            mountPath: /app
      volumes:
        - name: code
          hostPath:
            path: /minikube-host
            type: Directory
