apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: raft-chat-bot-marketing-web
  name: raft-chat-bot-marketing-web
  namespace: raft-chat-bot-marketing
spec:
  selector:
    matchLabels:
      app: raft-chat-bot-marketing-web
  replicas: 1
  template:
    metadata:
      labels:
        app: raft-chat-bot-marketing-web
    spec:
      containers:
      - image: raft-chat-bot-marketing-image:latest
        tty: true
        imagePullPolicy: Never
        name: raft-chat-bot-marketing-web
        command:
          - uvicorn
          - web:app
        volumeMounts:
          - name: code
            mountPath: /app
        ports:
          - containerPort: 8000
        env:
          - name: UVICORN_HOST
            value: 0.0.0.0
          - name: UVICORN_PORT
            value: "8000"
          - name: REDIS_URL
            value: REDIS_URL
          - name: ENVIRONMENT
            value: local
      volumes:
        - name: code
          hostPath:
            path: /minikube-host
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: raft-chat-bot-marketing-web-service
  namespace: raft-chat-bot-marketing
spec:
  type: NodePort
  selector:
    app: raft-chat-bot-marketing-web
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30001
