apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: raft-marketing-chat-bot-web
  name: raft-marketing-chat-bot-web
  namespace: default
spec:
  selector:
    matchLabels:
      app: raft-marketing-chat-bot-web
  replicas: 1
  template:
    metadata:
      labels:
        app: raft-marketing-chat-bot-web
    spec:
      containers:
      - image: raft-marketing-chat-bot:0.1.0
        imagePullPolicy: Never
        name: web
        command: ['uvicorn', 'main:app', '--reload']
        ports:
          - containerPort: 8000
        env:
          - name: UVICORN_HOST
            value: 0.0.0.0
          - name: UVICORN_PORT
            value: "8000"
          - name: REDIS_URL
            value: REDIS_URL
        tty: true
        volumeMounts:
          - name: code
            mountPath: /app
      volumes:
        - name: code
          hostPath:
            path: /raft-marketing-chat-bot
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: raft-marketing-chat-bot-web-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: raft-marketing-chat-bot-web
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30001
