apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: raft-marketing-chat-bot-worker-ai
  name: raft-marketing-chat-bot-worker-ai
  namespace: default
spec:
  selector:
    matchLabels:
      app: raft-marketing-chat-bot-worker-ai
  replicas: 1
  template:
    metadata:
      labels:
        app: raft-marketing-chat-bot-worker-ai
    spec:
      containers:
      - image: raft-marketing-chat-bot:0.1.0
        imagePullPolicy: Never
        name: worker-ai
        command: ['python', 'worker_ai.py']
        volumeMounts:
          - name: code
            mountPath: /app
      volumes:
        - name: code
          hostPath:
            path: /raft-marketing-chat-bot
            type: Directory
