apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
  namespace: raft-marketing-chat-bot
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: us-east1-docker.pkg.dev/raft-marketing-chat-bot/raft-marketing-chat-bot/raft-marketing-chat-bot:0.1.0
        imagePullPolicy: Always
        name: web
        command: ['uvicorn', 'main:app']
        ports:
          - containerPort: 8000
