apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker-aug
  name: worker-aug
  namespace: raft-chat-bot-marketing
spec:
  selector:
    matchLabels:
      app: worker-aug
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: worker-aug
    spec:
      containers:
      - image: gcs://.../raft-chat-bot-marketing-image:latest
        imagePullPolicy: IfNotPresent
        name: worker-aug
        command: ['python', 'worker_aug.py']
