apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker-ai
  name: worker-ai
  namespace: raft-marketing-chat-bot
spec:
  selector:
    matchLabels:
      app: worker-ai
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: worker-ai
    spec:
      containers:
      - image: us-east1-docker.pkg.dev/raft-marketing-chat-bot/raft-marketing-chat-bot/raft-marketing-chat-bot:0.1.0
        imagePullPolicy: Always
        name: worker-ai
        command: ['python', 'worker_ai.py']
