apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker-ai
  name: worker-ai
  namespace: raft-chat-bot-marketing
spec:
  selector:
    matchLabels:
      app: worker-ai
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: worker-ai
    spec:
      containers:
      - image: gcs://.../raft-chat-bot-marketing-image:latest
        imagePullPolicy: IfNotPresent
        name: worker-ai
        command: ['python', 'worker_ai.py']
